'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
const steps=['Object','Evidence','Context','Consent','Review'];
export function ContributionForm(){
  const [step,setStep]=useState(0); const [pending,setPending]=useState(false); const router=useRouter();
  const [form,setForm]=useState({kind:'Photograph',title:'1959 Aru village photograph',description:'The reverse of the photograph reads “Moonbird dancers, first rains, 1959.”',source:'Family archive of Ena Varo',date:'August 1959',place:'Aru village',consent:'public_attributed',requestedOutcome:'Correct the public label'});
  function field(key:string,value:string){setForm((x)=>({...x,[key]:value}));}
  async function submit(e:FormEvent){e.preventDefault();if(step<4){setStep(step+1);return;}setPending(true);const res=await fetch('/api/community/evidence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,objectId:'moonbird-mask'})});const data=await res.json();router.push(`/submissions/${data.id??'SUB-DEMO'}`);}
  return <form className="contribution-form" onSubmit={submit}>
    <aside><p className="eyebrow">Contribution</p><ol>{steps.map((s,i)=><li className={i===step?'active':i<step?'done':''} key={s}><span>{i<step?'✓':i+1}</span>{s}</li>)}</ol><p className="privacy-note">Your draft stays in this browser until you submit it. You control how the museum may use your contribution.</p></aside>
    <section className="form-stage">
      {step===0&&<><p className="form-count">Step 1 of 5</p><h1>Which object is this about?</h1><div className="selected-object"><span className="mini-mask"/><div><small>Selected object</small><strong>Moonbird Mask</strong><span>RT.1930.014 · Record open</span></div><button type="button">Change</button></div><p className="form-help">We’ll connect your contribution to this object’s record and open questions.</p></>}
      {step===1&&<><p className="form-count">Step 2 of 5</p><h1>What are you sharing?</h1><div className="choice-grid">{['Photograph','Document','Oral history','Object information'].map(x=><button type="button" className={form.kind===x?'selected':''} onClick={()=>field('kind',x)} key={x}><span>{x==='Photograph'?'▧':x==='Document'?'≡':x==='Oral history'?'◉':'◇'}</span>{x}</button>)}</div><label>Short title<input value={form.title} onChange={e=>field('title',e.target.value)}/></label></>}
      {step===2&&<><p className="form-count">Step 3 of 5</p><h1>Add the context you know.</h1><label>Description<textarea rows={5} value={form.description} onChange={e=>field('description',e.target.value)}/></label><div className="field-pair"><label>Date<input value={form.date} onChange={e=>field('date',e.target.value)}/></label><label>Place<input value={form.place} onChange={e=>field('place',e.target.value)}/></label></div><label>Where did this come from?<input value={form.source} onChange={e=>field('source',e.target.value)}/></label></>}
      {step===3&&<><p className="form-count">Step 4 of 5</p><h1>How may the museum use it?</h1><fieldset className="consent-options"><legend>Choose one permission</legend>{[['public_attributed','Public, with my name','The museum may quote and display this with attribution.'],['public_anonymous','Public, without my name','The museum may quote and display it without identifying me.'],['research_only','Research only','Curators may study it, but cannot quote or display it publicly.'],['private','Private','Only authorised curators may view it.']].map(([v,t,d])=><label key={v}><input type="radio" name="consent" checked={form.consent===v} onChange={()=>field('consent',v)}/><span><strong>{t}</strong><small>{d}</small></span></label>)}</fieldset></>}
      {step===4&&<><p className="form-count">Step 5 of 5</p><h1>Review your contribution.</h1><dl className="review-list"><div><dt>Object</dt><dd>Moonbird Mask</dd></div><div><dt>Evidence</dt><dd>{form.kind} · {form.title}</dd></div><div><dt>Context</dt><dd>{form.date} · {form.place}<br/>{form.source}</dd></div><div><dt>Permission</dt><dd>{form.consent.replaceAll('_',' ')}</dd></div></dl><div className="submission-notice"><b>What happens next</b><p>Your contribution will enter the curator inbox as <strong>submitted</strong>. It can inform research, but it cannot change the official record by itself.</p></div></>}
      <div className="form-actions">{step>0&&<button type="button" className="secondary-action" onClick={()=>setStep(step-1)}>Back</button>}<button className="primary-action" disabled={pending}>{step===4?(pending?'Submitting…':'Submit contribution'):'Continue'} <span>→</span></button></div>
    </section>
  </form>;
}
