'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ReactNode, useEffect, useRef, useState } from 'react';
import { registerWebMcpTools } from '@/lib/webmcp/register';

export function CuratorShell({children}:{children:ReactNode}){
  const path=usePathname(); const [drawer,setDrawer]=useState(false); const [draft,setDraft]=useState('The mask appears in a 1959 community photograph from Aru village. Its movement and acquisition circumstances from 1959 to 1968 remain under joint research.'); const [resolved,setResolved]=useState('');
  const drawerRef=useRef<HTMLElement>(null);
  useEffect(()=>registerWebMcpTools('curator'),[]);
  useEffect(()=>{const open=()=>setDrawer(true);window.addEventListener('open-approval',open);return()=>window.removeEventListener('open-approval',open)},[]);
  useEffect(()=>{if(!drawer)return;const panel=drawerRef.current;const focusable=panel?.querySelectorAll<HTMLElement>('button, textarea, [href]');focusable?.[0]?.focus();const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape')setDrawer(false);if(event.key==='Tab'&&focusable?.length){const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener('keydown',keyboard);return()=>document.removeEventListener('keydown',keyboard)},[drawer]);
  async function community(){await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role:'community'})});location.href='/';}
  async function resolve(action:'approved'|'rejected'){const result=await fetch('/api/curator/approvals/APR-004/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,draft})});setResolved(result.ok?action:'Could not save');if(result.ok)setTimeout(()=>setDrawer(false),900)}
  return <div className="console-shell">
    <header className="console-topbar"><Link className="wordmark inverse" href="/curator">RE<span>:</span>TURN</Link><div className="console-context"><b>Halcyon Museum</b><span>Curatorial workspace</span></div><div className="console-actions"><button className="approval-trigger" onClick={()=>setDrawer(true)}><i>1</i> Pending approval</button><button className="role-switch dark" onClick={community}>Community view ↗</button><span className="avatar">MK</span></div></header>
    <aside className="console-nav"><div><small>Workspace</small>{[['/curator','Overview','⌂'],['/curator/submissions','Submissions','↓'],['/curator/objects','Objects','◇'],['/curator/activity','Activity','≋']].map(([href,label,icon])=><Link className={path===href?'active':''} href={href} key={href}><span>{icon}</span>{label}{label==='Submissions'&&<b>3</b>}</Link>)}</div><div><small>System</small><button>◉ Policy gateway</button><button>⌘ WebMCP tools <b className="tool-count">12</b></button></div><p>Demo workspace<br/><strong>Fictional collection</strong></p></aside>
    <div className="console-content">{children}</div>
    {drawer&&<><button className="drawer-scrim" aria-label="Close approval drawer" onClick={()=>setDrawer(false)}/><aside ref={drawerRef} className="approval-drawer" role="dialog" aria-modal="true" aria-labelledby="approval-title"><header><div><p className="risk-label">High risk · Official record</p><h2 id="approval-title">Review label revision</h2><span>APR-004 · Moonbird Mask</span></div><button onClick={()=>setDrawer(false)} aria-label="Close">×</button></header>{resolved?<div className="resolved-state"><span>✓</span><h3>{resolved==='approved'?'Revision approved':'Proposal rejected'}</h3><p>{resolved==='approved'?'Revision 4 is now the public record.':'No change was made to the public record.'}</p></div>:<><section className="policy-decision"><span>Policy Gateway</span><strong>Human approval required</strong><p>Official publication changes what the public sees. Evidence authority and consent checks passed.</p></section><section><h3>Evidence in this proposal</h3><div className="evidence-ref"><span>EV-059</span><p>1959 community photograph</p><i className="submitted-badge">Submitted</i></div><div className="evidence-ref"><span>EV-068</span><p>1968 gallery invoice</p><i className="verified-badge">Verified</i></div></section><section><h3>Current label</h3><p className="before-copy"><del>Legally acquired from Lorne Gallery in 1968.</del></p><h3>Curator-edited version</h3><textarea aria-label="Curator-edited label" rows={6} value={draft} onChange={e=>setDraft(e.target.value)}/><div className="assertion-summary"><span><i className="verified-dot"/>Verified fact · EV-068</span><span><i className="claim-dot"/>Attributed claim · EV-059</span><span><i className="question-dot"/>Open question · EV-059, EV-068</span></div></section><footer><button className="reject-action" onClick={()=>resolve('rejected')}>Reject</button><button className="approve-action" onClick={()=>resolve('approved')}>Approve with edit <span>→</span></button></footer></>}</aside></>}
  </div>;
}
